---
--- Generated by Luanalysis
--- Created by L--N.
--- DateTime: 2023/6/15 19:10
---
---优惠卷id
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]
-- 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 下单的用户key     set集合保证一人一单
local orderKey = 'seckill:order:' .. voucherId
-- 库存不足返回1
if (tonumber(redis.call('get',stockKey)) <= 0) then
    return 1
end
-- 以下过单返回2
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
-- 减库存
redis.call('incrby', stockKey, -1)
-- 用户添加到已下单集合
redis.call('sadd', orderKey, userId)
return 0