logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.41.134
    port: 5672
    virtual-host: /
    username: lee
    password: 123456
    listener:
      simple:
        prefetch: 1